[package]
name = "pulz-ecs"
description = "High-performance Entity Component System (ECS) built on pulz-schedule."
keywords = ["ecs", "game-engine", "entity-component-system"]
categories = ["game-engines", "data-structures"]
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
pulz-schedule.workspace = true
pulz-ecs-macros = { version = "=0.1.0-alpha2", path = "macros" }
pulz-functional-utils.workspace = true
slotmap.workspace = true
roaring.workspace = true
bit-set.workspace = true
