[package]
name = "run-wasm"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
cargo-run-wasm = "0.3.0"
